language:
    - php

php:
    - 5.5
    - 5.6

before_script:
   - pear config-set auto_discover 1
   - pear install PHP_CodeSniffer
   - phpenv rehash
   - phpcs -i

script:
    - phpcs --standard=PSR2 . --extensions=php

notifications:
    slack: sqweb:6itfzHb8hydraMDj5Gk8kkVE
